### ISSUE TITLE
LineageOS 19.1 (April 2023) for G920F/G925F sim are not working 

### ISSUE THREAD

**Issue by MehediHasannOvi** [fakemanoan/LineageOS-Releases#31] opened 2023-04-17 02:28 UTC
when i Update to LineageOS 19.1 (April 2023) for G920F/G925F my Sim are not working phone can't find to sim card

**Comment by hamzamaqsood877** [comment] 2023-04-20 09:18
working on my side, although, I did a clean install

**Comment by fakemanoan** [comment] 2023-04-20 20:47
this may be due to updates to the APNs? I don't think that should cause your SIM to not be detected though. verify that your SIM is inserted correctly and that you are getting IMEI information in the about section of settings

**Comment by MehediHasannOvi** [comment] 2023-04-21 03:11
i also clean install , but sim ar not show , i also change sim , but not working , than i back to lineage-19.1-20230322-UNOFFICIAL-zerofltexx now sim are working but voice call problem 
Device - Sm-G920f , one sim

**Comment by MehediHasannOvi** [comment] 2023-04-21 03:12
> working on my side, although, I did a clean install

i also clean install but sim is not working

**Comment by hamzamaqsood877** [comment] 2023-04-21 03:25
From settings>about phone>software info check if baseband is there and also check imei by dialing *#06#

**Comment by hamzamaqsood877** [comment] 2023-04-21 03:27
> > working on my side, although, I did a clean install
> 
> i also clean install but sim is not working

From settings>about phone>software info check if baseband is there and also check imei by dialing
 ```
*#06#
```

**Comment by MehediHasannOvi** [comment] 2023-04-21 05:26
> > > working on my side, although, I did a clean install
> > 
> > 
> > i also clean install but sim is not working
> 
> From settings>about phone>software info check if baseband is there and also check imei by dialing
> 
> ```
> *#06#
> ```

imei not detect. Showing blank. SIM status Not Availble Slow 
**Image**
[https://drive.google.com/drive/folders/1MEv5sbG6JF66QzwiP9HNiYmopbHsRx5a?usp=share_link](url)

**Comment by MehediHasannOvi** [comment] 2023-04-21 05:27
> this may be due to updates to the APNs? I don't think that should cause your SIM to not be detected though. verify that your SIM is inserted correctly and that you are getting IMEI information in the about section of settings

imei not detect. Showing blank. SIM status Not Availble Slow


**Image**
Image
[https://drive.google.com/drive/folders/1MEv5sbG6JF66QzwiP9HNiYmopbHsRx5a?usp=share_link](url)

**Comment by fakemanoan** [comment] 2023-04-21 13:45
Take a screenshot of the android version details in settings. 

Post an 'adb logcat -b all' when booting if you can. Ideally in a PM just to be safe.

**Comment by MehediHasannOvi** [comment] 2023-04-22 00:14
android version details  add 

i don't know how to do this 'adb logcat -b all

[https://drive.google.com/drive/folders/1MEv5sbG6JF66QzwiP9HNiYmopbHsRx5a](url)

**Comment by MehediHasannOvi** [comment] 2023-04-22 00:15
> Take a screenshot of the android version details in settings.
> 
> Post an 'adb logcat -b all' when booting if you can. Ideally in a PM just to be safe.

 android version details  add 

i don't know how to do this 'adb logcat -b all

[https://drive.google.com/drive/folders/1MEv5sbG6JF66QzwiP9HNiYmopbHsRx5a](url)

@fakemanoan

**Comment by hamzamaqsood877** [comment] 2023-04-22 04:41
To take logs from ADB you will need 

1. PC/Laptop
2. Samsung and ADB Drivers Installed in PC
3. ADB Tools Package
4. Your Phone and Brain

First, install above-mentioned drivers and then connect your phone to pc.
On your phone screen check always allow ootion when appear.
Then extract ADB Tools zip file anywhere and open Command Propmt from there (Press Shift+Right Mouse Button abd then choose Open Command Propmt here)
After opening cmd window check if your phone is connected or not by giving command "adb devices" (without commas) and if your device appears then your phone is good to go for taking logs
To take logs then turn off phone and give adb log command which fakemon told in his comment. You'll see waiting for device and then turn on the phone and waut for logs being collected.
After your device boots up completely, you can stop command by pressing Crtl+C and a log file will be saved there.
I hope this guide will help.

**Comment by amjeed-ay** [comment] 2023-08-05 22:42
I got same issue, sim not detected on g920f dualsim

**Comment by harshdeeep** [comment] 2023-11-25 10:40
im using lineage 19.1 sim and mobile data are working just voice calls dont work , like if i call someone it doesnt it cuts automatically and no one can call me.

**Comment by MehediHasannOvi** [comment] 2023-11-25 12:57
same problem last release

**Comment by fakemanoan** [comment] 2024-03-12 10:02
Hi can you please confirm if this issue is resolved in the latest 19.1 build?

**Comment by MehediHasannOvi** [comment] 2024-03-13 10:46
> Hi can you please confirm if this issue is resolved in the latest 19.1 build?

I will use 20-20240119 when I call someone I can't recived  have any sound or voice in sim call, online calls are working fine

**Comment by fakemanoan** [comment] 2024-03-13 11:24
As the issue originally related to lineage 19.1 I asked about that first. 20 has not yet received an update to address this, which should be today

**Comment by fakemanoan** [comment] 2024-03-13 16:53
Update for 20 dropped. Please retest if you can

**Comment by MehediHasannOvi** [comment] 2024-03-27 10:56
> Update for 20 dropped. Please retest if you can

bro new update internet meter are not working

**Comment by fakemanoan** [comment] 2024-03-27 11:05
Lineage 20 never supported showing the network speed, as it requires eBPF (if thats what you are referring to)

Detailed explanation here:
https://github.com/fakemanoan/LineageOS-Releases/issues/75#issuecomment-1962390190

if your sim is working this issue is resolved

**Comment by fakemanoan** [comment] 2024-03-27 15:44
What version did you flash?

**Comment by fakemanoan** [comment] 2024-03-28 11:07
What version _*specifically*_ did you flash? Name of the zip will suffice. 

If it is 20240313 or 20240311, then please provide "adb logcat -b all" logs after you encounter the issue. If you need help capturing logs have a read here: https://wiki.lineageos.org/how-to/logcat/

**Comment by fakemanoan** [comment] 2024-03-31 10:22
Are you able to provide logs? If you can't then I can't fix the problem as I can't reproduce it

**Comment by MehediHasannOvi** [comment] 2024-04-03 08:15
> Are you able to provide logs? If you can't then I can't fix the problem as I can't reproduce it

[Uploading logcat.txt…]()

**Comment by MehediHasannOvi** [comment] 2024-04-03 08:16
> Are you able to provide logs? If you can't then I can't fix the problem as I can't reproduce it

[Uploading logcat.txt…]()

**Comment by MehediHasannOvi** [comment] 2024-04-03 08:20
> Are you able to provide logs? If you can't then I can't fix the problem as I can't reproduce it

https://drive.google.com/file/d/1kyMs_t5US52G5ofxmMeGBe0DOCiv44tH/view?usp=sharing

**Comment by fakemanoan** [comment] 2024-04-15 09:16
try the newest build at <https://fakemanoan.github.io>.

Make sure you remove your sim lock prior to flashing, as that causes some issues with the new RIL.

**Comment by MehediHasannOvi** [comment] 2024-04-18 03:19
> Remove your sim lock prior to flashing

I will flash new update calls are not working, sim are unlock

**Closed** 2024-11-28 11:34 UTC
Labels: needs retest
